/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EEmployeeFiltersRouteImport } from './routes/e/employee-filters'
import { Route as EDemoAnnotationsRouteImport } from './routes/e/demo-annotations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EEmployeeFiltersRoute = EEmployeeFiltersRouteImport.update({
  id: '/e/employee-filters',
  path: '/e/employee-filters',
  getParentRoute: () => rootRouteImport,
} as any)
const EDemoAnnotationsRoute = EDemoAnnotationsRouteImport.update({
  id: '/e/demo-annotations',
  path: '/e/demo-annotations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e/demo-annotations': typeof EDemoAnnotationsRoute
  '/e/employee-filters': typeof EEmployeeFiltersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e/demo-annotations': typeof EDemoAnnotationsRoute
  '/e/employee-filters': typeof EEmployeeFiltersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e/demo-annotations': typeof EDemoAnnotationsRoute
  '/e/employee-filters': typeof EEmployeeFiltersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e/demo-annotations' | '/e/employee-filters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e/demo-annotations' | '/e/employee-filters'
  id: '__root__' | '/' | '/e/demo-annotations' | '/e/employee-filters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EDemoAnnotationsRoute: typeof EDemoAnnotationsRoute
  EEmployeeFiltersRoute: typeof EEmployeeFiltersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/employee-filters': {
      id: '/e/employee-filters'
      path: '/e/employee-filters'
      fullPath: '/e/employee-filters'
      preLoaderRoute: typeof EEmployeeFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/demo-annotations': {
      id: '/e/demo-annotations'
      path: '/e/demo-annotations'
      fullPath: '/e/demo-annotations'
      preLoaderRoute: typeof EDemoAnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EDemoAnnotationsRoute: EDemoAnnotationsRoute,
  EEmployeeFiltersRoute: EEmployeeFiltersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
